name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change this based on your project needs

      - name: Install dependencies
        run: make install

      - name: Lint Code
        run: make lint

      - name: Run Unit Tests
        run: make test
